### ISSUE TITLE
Missing the parameter pq_features when I run the train_better.py file

### ISSUE THREAD

**Issue by RaincccY** [manoja328/rodeo#4]
Hi, an error occurs when I run the train_better.py file:
```
Traceback (most recent call last):
  File "train_better.py", line 296, in <module>
    loss_dict = model(images, targets)
  File "/home/cy/.conda/envs/RODEO/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cy/rodeo-master/frcnn_mod.py", line 57, in forward
    raise ValueError("In training mode, targets should be passed")
ValueError: In training mode, targets should be passed
```
I find I need a parameter **pq_features** here:
https://github.com/manoja328/rodeo/blob/c7f340a1749fd7cc9be8a6b14d7ffb95c60aa78e/frcnn_mod.py#L43-L77
but in train_better.py file, there are only **images** and **targets**:
https://github.com/manoja328/rodeo/blob/c7f340a1749fd7cc9be8a6b14d7ffb95c60aa78e/train_better.py#L294
Is the problem here? How to solve it?
Looking for your reply. Thanks.

**Comment by OpenAI2022** [comment]
I guess you can swap forward and forward00

**Comment by manoja328** [comment]
Yes thats correct. At the time I didnot have a good logic to do it but essententially  if you just images use the forward and if using pq features use the forward00 method.

**Comment by RaincccY** [comment]
I see. Thanks a lot.
